# Generated by Django 5.2.1 on 2025-05-30 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('phone', models.CharField(default='', max_length=20)),
                ('bio', models.TextField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('cvDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cvdoc')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('experience', models.IntegerField()),
                ('cvDoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cvdoc')),
            ],
        ),
    ]
