# Generated by Django 5.2.1 on 2025-06-01 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvdoc',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='cvdoc',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='cvDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='main.cvdoc'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='cvDoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.cvdoc'),
        ),
        migrations.AddIndex(
            model_name='cvdoc',
            index=models.Index(fields=['id', 'lastname'], name='main_cvdoc_id_15f234_idx'),
        ),
    ]
