# Generated by Django 5.2.1 on 2025-06-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cvdoc_bio_alter_cvdoc_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['startDate']},
        ),
        migrations.RemoveField(
            model_name='cvdoc',
            name='bio',
        ),
        migrations.AddField(
            model_name='cvdoc',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
