# Generated by Django 5.2.1 on 2025-06-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_requestlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cvdoc',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'CVs'},
        ),
        migrations.AlterField(
            model_name='skill',
            name='experience',
            field=models.IntegerField(verbose_name='Years'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Skill'),
        ),
    ]
