# Generated by Django 5.2.1 on 2025-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cvdoc_options_alter_skill_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvdoc',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
